### ISSUE TITLE
[Feature request] Add action typing

### ISSUE THREAD

**Issue by krzema12** [axel-op/googlejavaformat-action#22]
Hi @axel-op!

Maintainer of https://github.com/krzema12/github-actions-kotlin-dsl here. Your action havs first-class support in the library. In short, the library provides a Kotlin type-safe API to create GitHub workflows.

Recently we've come up with a way to reduce operational load when keeping library's action wrappers in sync with actions' inputs. The solution includes onboarding https://github.com/krzema12/github-actions-typing. It's as easy as adding an extra YAML file to your repository root, and adding a simple GitHub workflow that validates this new file. Thanks to this, the code generator in the Kotlin DSL can fetch typing info provided by you instead of us, which has a number of benefits. It has no negative effects on current action consumers, they continue to use the action via regular GitHub API, as if the file wasn't there.

In this feature request, I would like to ask you if you're open to introducing such typings in your actions. You wouldn't be first - there's already another action using it: https://github.com/Vampire/setup-wsl

If your answer is "yes", feel free to either add it yourself, or let me know - me or some of my fellow contributors would be happy to post a PR. We're also open to any kind of questions and feedback.

**Comment by axel-op** [comment]
Hello @krzema12, sorry for the delayed response. You can definitely send a PR and I'll review it!

**Comment by krzema12** [comment]
@axel-op cool, here's the PR: https://github.com/axel-op/googlejavaformat-action/pull/26

In the meantime (after I created this ticket), a bunch of other actions introduced the typings: https://github.com/krzema12/github-actions-typing/network/dependents so yours definitely wouldn't be alone :smile:

Happy to answer any questions!
