### ISSUE TITLE
Please fix typings and release

### ISSUE THREAD

**Issue by krzema12** [axel-op/googlejavaformat-action#30]
Hi @axel-op!

This is a little follow-up after #22 and #26. I'd like to use the typings in one of my projects, but they are now broken because of the extra deprecated inputs (discussed in https://github.com/typesafegithub/github-actions-typing/issues/110) and also there's no release (major version tag or branch) that would point to a commit already with `action-types.yml`. Here's a kind request to fix both issues 😊

Best,
Piotr

**Comment by axel-op** [comment]
Hello,

I've removed the deprecated inputs from the `master` branch and the "type validation" workflow now passes. I don't plan to merge this commit to another branch for now, so you should be able to make your project work by pointing it to the `master` branch :)
